version: '2'
services:
  db:
    image: mysql:latest
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data/:/var/lib/mysql/
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      MYSQL_HOST: db
    volumes:
      - ./hitparade/:/code/
      - ./docker/entrypoint.sh:/code/entrypoint.sh
    ports:
      - "80:80"
    depends_on:
      - db
    links:
      - db:db
