# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-03 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='colors',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='team',
            name='hashtags',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='division',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.Conference'),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_game', to='hitparade.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_game', to='hitparade.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winning_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_game', to='hitparade.Team'),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hitparade.Team'),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='hp_ump',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_stat', to='hitparade.Official'),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='opp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hitparade.Team'),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='opp_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hitparade.Player'),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='opp_pit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hitparade.Player'),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_stat', to='hitparade.Player'),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_stat', to='hitparade.Venue'),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_stat', to='hitparade.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.Conference'),
        ),
    ]
