# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0001_squashed_0016_auto_20170509_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ss_id', models.CharField(max_length=36, unique=True)),
                ('at_bat_balls', models.IntegerField(null=True)),
                ('at_bat_outs', models.IntegerField(null=True)),
                ('at_bat_pitch_count', models.IntegerField(null=True)),
                ('at_bat_strikes', models.IntegerField(null=True)),
                ('even_count', models.NullBooleanField()),
                ('full_count', models.NullBooleanField()),
                ('half', models.CharField(max_length=2, null=True)),
                ('hit_location', models.NullBooleanField()),
                ('hit_type', models.NullBooleanField()),
                ('hitter_pitch_count', models.CharField(max_length=3, null=True)),
                ('inning', models.IntegerField(null=True)),
                ('inning_label', models.CharField(max_length=32, null=True)),
                ('is_at_bat', models.NullBooleanField()),
                ('is_at_bat_over', models.NullBooleanField()),
                ('is_bunt', models.NullBooleanField()),
                ('is_bunt_shown', models.NullBooleanField()),
                ('is_double_play', models.NullBooleanField()),
                ('is_hit', models.NullBooleanField()),
                ('is_on_base', models.NullBooleanField()),
                ('is_passed_ball', models.NullBooleanField()),
                ('is_triple_play', models.NullBooleanField()),
                ('is_wild_pitch', models.NullBooleanField()),
                ('pitch_count', models.IntegerField(null=True)),
                ('pitch_name', models.CharField(max_length=32, null=True)),
                ('pitch_outcome', models.CharField(max_length=32, null=True)),
                ('pitch_outcome_type', models.CharField(max_length=32, null=True)),
                ('pitch_speed', models.FloatField(null=True)),
                ('pitch_type', models.CharField(max_length=8, null=True)),
                ('pitch_zone', models.IntegerField(null=True)),
                ('sequence', models.IntegerField(null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitch', to='hitparade.Game')),
                ('hitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hitparade.Player')),
                ('hitter_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hitparade.Team')),
                ('pitched_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hitparade.Venue')),
                ('pitcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hitparade.Player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hitparade.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
