# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-03 20:39
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0002_auto_20170503_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='colors',
            field=django_mysql.models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='team',
            name='hashtags',
            field=django_mysql.models.JSONField(default=list),
        ),
    ]
