# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0002_pitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='pitched_at',
            field=models.DateTimeField(null=True),
        ),
    ]
