# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0003_auto_20170503_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
