# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0004_auto_20170503_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.Division'),
        ),
    ]
