# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0004_auto_20170510_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtBat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ss_id', models.CharField(max_length=36, unique=True)),
                ('description', models.CharField(max_length=64, null=True)),
                ('half', models.CharField(max_length=2, null=True)),
                ('inning', models.IntegerField(null=True)),
                ('inning_label', models.CharField(max_length=32, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_bats', to='hitparade.Game')),
                ('hitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_bats', to='hitparade.Player')),
                ('hitter_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hitparade.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
