# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0005_auto_20170503_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='captain',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='handedness',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='high_school',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='humanized_salary',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position_abbreviation',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='salary_currency',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='school',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='unit_of_height',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='unit_of_weight',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
