# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0005_atbat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atbat',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
