# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0006_auto_20170510_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='at_bat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_bat', to='hitparade.AtBat'),
        ),
    ]
