# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0006_auto_20170503_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='draft_team_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
