# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0007_auto_20170503_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
