# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0008_game_at_bats_loaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AlterIndexTogether(
            name='player',
            index_together=set([('nickname', 'last_name')]),
        ),
    ]
