# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0008_auto_20170504_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='field_type',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='stadium_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='time_zone',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
