# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0009_auto_20170504_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='humidity',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='internet_coverage',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='interval',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='label',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='on',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='period_label',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='satellite_coverage',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='scoreline',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='television_coverage',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='temperature',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='temperature_unit',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='weather_conditions',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='wind_direction',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='wind_speed_unit',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
