# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0009_auto_20170516_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitch',
            options={'verbose_name_plural': 'Pitches'},
        ),
        migrations.AddField(
            model_name='gamestat',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='hitparade.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='hitparade.Team'),
        ),
    ]
