# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0010_auto_20170519_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestat',
            name='ba14',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='ba7',
            field=models.FloatField(null=True),
        ),
    ]
