# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-27 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0011_auto_20170619_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='venue',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.Venue'),
        ),
    ]
