# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0012_team_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='country',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='distances_cf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='distances_lcf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='distances_lf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='distances_mlcf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='distances_mlf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='distances_mrcf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='distances_mrf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='distances_rcf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='distances_rf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='market',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='sr_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='surface',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='zipcode',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
