# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0012_team_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBattingLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('position', models.CharField(max_length=4, null=True)),
                ('handedness', models.CharField(max_length=4, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.Game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.Player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
