# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-16 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0013_gamebattinglineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='official',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.Official'),
        ),
        migrations.AddField(
            model_name='game',
            name='starting_away_pitcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_pitcher', to='hitparade.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='starting_home_pitcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_pitcher', to='hitparade.Player'),
        ),
        migrations.AddField(
            model_name='official',
            name='base_on_balls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='base_on_balls_per_inning',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='batting_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='games',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='innings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='on_base_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='on_base_plus_slugging',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='runs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='runs_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='slugging_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='strike_outs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='strikes_per_inning',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
