# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0014_team_sr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_city',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_country',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='preferred_name',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='primary_position',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sr_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sr_status',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
