# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0014_auto_20170504_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestat',
            name='local_game_time',
            field=models.DateTimeField(null=True),
        ),
    ]
