# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-19 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0015_rotowirescrapelineuplog_rotowirescrapeofficiallog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='runs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
