# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0015_auto_20170504_1917'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamestat',
            unique_together=set([('player', 'car_game_num')]),
        ),
    ]
