# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0015_auto_20171006_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorsOverall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('throwing', models.IntegerField(null=True)),
                ('fielding', models.IntegerField(null=True)),
                ('interference', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ab', models.IntegerField(null=True)),
                ('runs', models.IntegerField(null=True)),
                ('s', models.IntegerField(null=True)),
                ('t', models.IntegerField(null=True)),
                ('hr', models.IntegerField(null=True)),
                ('rbi', models.IntegerField(null=True)),
                ('bb', models.IntegerField(null=True)),
                ('ibb', models.IntegerField(null=True)),
                ('hbp', models.IntegerField(null=True)),
                ('sb', models.IntegerField(null=True)),
                ('cs', models.IntegerField(null=True)),
                ('obp', models.IntegerField(null=True)),
                ('slg', models.FloatField(null=True)),
                ('ops', models.FloatField(null=True)),
                ('ktotal', models.IntegerField(null=True)),
                ('h', models.IntegerField(null=True)),
                ('avg', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sr_id', models.CharField(blank=True, max_length=36, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('market', models.CharField(blank=True, max_length=64, null=True)),
                ('abbr', models.CharField(blank=True, max_length=64, null=True)),
                ('split', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.Split')),
                ('team', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
