# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0016_auto_20170719_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='runs_scored',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
