# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0016_errorsoverall_split_teamsplit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldingOverall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('po', models.IntegerField(null=True)),
                ('a', models.IntegerField(null=True)),
                ('dp', models.IntegerField(null=True)),
                ('tp', models.IntegerField(null=True)),
                ('error', models.IntegerField(null=True)),
                ('tc', models.IntegerField(null=True)),
                ('fpct', models.IntegerField(null=True)),
                ('c_wp', models.IntegerField(null=True)),
                ('pb', models.IntegerField(null=True)),
                ('rf', models.FloatField(null=True)),
                ('errors', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.ErrorsOverall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GamesOverall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.IntegerField(null=True)),
                ('play', models.IntegerField(null=True)),
                ('finish', models.IntegerField(null=True)),
                ('complete', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fieldingoverall',
            name='games',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.GamesOverall'),
        ),
    ]
