# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-27 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0017_auto_20170719_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='base_on_balls_per_inning',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='batting_average',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='innings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='on_base_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='on_base_plus_slugging',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='runs_scored',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='slugging_average',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='strikes_per_inning',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
