# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0017_auto_20171006_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='StealOverall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('caught', models.IntegerField(null=True)),
                ('stolen', models.IntegerField(null=True)),
                ('pct', models.IntegerField(null=True)),
                ('pickoff', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
