# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0018_stealoverall'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsOverall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('po', models.IntegerField(null=True)),
                ('fo', models.IntegerField(null=True)),
                ('fidp', models.IntegerField(null=True)),
                ('lo', models.IntegerField(null=True)),
                ('lidp', models.IntegerField(null=True)),
                ('go', models.IntegerField(null=True)),
                ('gidp', models.IntegerField(null=True)),
                ('klook', models.IntegerField(null=True)),
                ('kswing', models.IntegerField(null=True)),
                ('ktotal', models.IntegerField(null=True)),
                ('sacfly', models.IntegerField(null=True)),
                ('sachit', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
