# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0020_onbaseoverall_outcomeoverall'),
    ]

    operations = [
        migrations.CreateModel(
            name='HittingOverall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ab', models.IntegerField(null=True)),
                ('lob', models.IntegerField(null=True)),
                ('rbi', models.IntegerField(null=True)),
                ('abhr', models.FloatField(null=True)),
                ('abk', models.FloatField(null=True)),
                ('bip', models.IntegerField(null=True)),
                ('babip', models.FloatField(null=True)),
                ('bbk', models.FloatField(null=True)),
                ('bbpa', models.FloatField(null=True)),
                ('iso', models.FloatField(null=True)),
                ('obp', models.FloatField(null=True)),
                ('ops', models.FloatField(null=True)),
                ('seca', models.FloatField(null=True)),
                ('slg', models.FloatField(null=True)),
                ('xbh', models.FloatField(null=True)),
                ('pitch_count', models.IntegerField(null=True)),
                ('lob_risp_2out', models.IntegerField(null=True)),
                ('team_lob', models.IntegerField(null=True)),
                ('ab_risp', models.IntegerField(null=True)),
                ('hit_risp', models.IntegerField(null=True)),
                ('rbi_2out', models.IntegerField(null=True)),
                ('linedrive', models.IntegerField(null=True)),
                ('groundball', models.IntegerField(null=True)),
                ('popup', models.IntegerField(null=True)),
                ('flyball', models.IntegerField(null=True)),
                ('ap', models.IntegerField(null=True)),
                ('avg', models.FloatField(null=True)),
                ('gofo', models.FloatField(null=True)),
                ('runs', models.IntegerField(null=True)),
                ('games', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.GamesOverall')),
                ('onbase', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.OnBaseOverall')),
                ('outcome', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.OutcomeOverall')),
                ('outs', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.OutsOverall')),
                ('steal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hitparade.StealOverall')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
