# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0021_hittingoverall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sr_id', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.IntegerField(null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('fielding_statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitparade.FieldingOverall')),
                ('hitting_statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitparade.HittingOverall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='seasons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season', to='hitparade.Season'),
        ),
    ]
