# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0023_hittingoverall_hitting_overall_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='hittingoverall',
            name='day_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_split', to='hitparade.Split'),
        ),
        migrations.AlterField(
            model_name='hittingoverall',
            name='hitting_overall_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hitting_overall_split', to='hitparade.Split'),
        ),
    ]
