# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0024_auto_20171006_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='hittingoverall',
            name='april_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='april_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='august_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='august_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='grass_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grass_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='home_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='july_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='july_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='june_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='june_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='left_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='march_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='march_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='may_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='may_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='night_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='night_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='november_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='november_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='october_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='october_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='right_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='september_split',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='september_split', to='hitparade.Split'),
        ),
        migrations.AddField(
            model_name='hittingoverall',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_team', to='hitparade.Team'),
        ),
    ]
