# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitparade', '0025_auto_20171006_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='hittingoverall',
            name='opponent_offense_split',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_offense_split', to='hitparade.TeamSplit'),
        ),
    ]
