"""empty message

Revision ID: 272cddca956e
Revises: f81f5d9e0f90
Create Date: 2017-05-01 20:07:59.239868

"""

# revision identifiers, used by Alembic.
revision = '272cddca956e'
down_revision = 'f81f5d9e0f90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamestat',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('local_game_time', sa.DateTime(), nullable=True),
    sa.Column('home_team', sa.Integer(), nullable=True),
    sa.Column('opp', sa.Integer(), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('hp_ump', sa.Integer(), nullable=True),
    sa.Column('opp_cat', sa.Integer(), nullable=True),
    sa.Column('opp_pit', sa.Integer(), nullable=True),
    sa.Column('player', sa.Integer(), nullable=True),
    sa.Column('stadium', sa.Integer(), nullable=True),
    sa.Column('ab', sa.Integer(), nullable=True),
    sa.Column('ba14', sa.Integer(), nullable=True),
    sa.Column('ba7', sa.Integer(), nullable=True),
    sa.Column('ba_curr_month', sa.Integer(), nullable=True),
    sa.Column('bb', sa.Integer(), nullable=True),
    sa.Column('car_ba', sa.Float(), nullable=True),
    sa.Column('car_ba_bip', sa.Float(), nullable=True),
    sa.Column('car_ba_curr_month', sa.Float(), nullable=True),
    sa.Column('car_ba_for_half', sa.Float(), nullable=True),
    sa.Column('car_ba_in_park', sa.Float(), nullable=True),
    sa.Column('car_ba_off_pit', sa.Float(), nullable=True),
    sa.Column('car_ba_vs_lhp', sa.Float(), nullable=True),
    sa.Column('car_ba_vs_opp', sa.Float(), nullable=True),
    sa.Column('car_ba_vs_rhp', sa.Float(), nullable=True),
    sa.Column('car_ba_with_ump', sa.Float(), nullable=True),
    sa.Column('car_era_with_ump', sa.Float(), nullable=True),
    sa.Column('car_game_num', sa.Integer(), nullable=True),
    sa.Column('curr_hit_streak', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Integer(), nullable=True),
    sa.Column('gidp', sa.Integer(), nullable=True),
    sa.Column('game_num', sa.Integer(), nullable=True),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('hbp', sa.Integer(), nullable=True),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('half', sa.Integer(), nullable=True),
    sa.Column('ibb', sa.Integer(), nullable=True),
    sa.Column('is_opp_pit_rhp', sa.Integer(), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('opp_bullpen_era', sa.Float(), nullable=True),
    sa.Column('opp_pit_car_era', sa.Float(), nullable=True),
    sa.Column('opp_pit_car_l', sa.Float(), nullable=True),
    sa.Column('opp_pit_car_w', sa.Float(), nullable=True),
    sa.Column('opp_pit_era', sa.Float(), nullable=True),
    sa.Column('opp_pit_l', sa.Integer(), nullable=True),
    sa.Column('opp_pit_w', sa.Integer(), nullable=True),
    sa.Column('opp_score', sa.Integer(), nullable=True),
    sa.Column('pa', sa.Float(), nullable=True),
    sa.Column('player_team_score', sa.Integer(), nullable=True),
    sa.Column('r', sa.Integer(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('roe', sa.Integer(), nullable=True),
    sa.Column('sac', sa.Integer(), nullable=True),
    sa.Column('sb', sa.Integer(), nullable=True),
    sa.Column('sf', sa.Integer(), nullable=True),
    sa.Column('sea_ba', sa.Float(), nullable=True),
    sa.Column('sea_ba_bip', sa.Float(), nullable=True),
    sa.Column('sea_ba_for_half', sa.Float(), nullable=True),
    sa.Column('sea_ba_in_park', sa.Float(), nullable=True),
    sa.Column('sea_ba_vs_lhp', sa.Float(), nullable=True),
    sa.Column('sea_ba_vs_opp', sa.Float(), nullable=True),
    sa.Column('sea_ba_vs_rhp', sa.Float(), nullable=True),
    sa.Column('sea_ba_with_ump', sa.Float(), nullable=True),
    sa.Column('sea_era_with_ump', sa.Float(), nullable=True),
    sa.Column('triples', sa.Integer(), nullable=True),
    sa.Column('was_start', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['home_team'], ['team.id'], ),
    sa.ForeignKeyConstraint(['hp_ump'], ['official.id'], ),
    sa.ForeignKeyConstraint(['opp'], ['team.id'], ),
    sa.ForeignKeyConstraint(['opp_cat'], ['player.id'], ),
    sa.ForeignKeyConstraint(['opp_pit'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player'], ['player.id'], ),
    sa.ForeignKeyConstraint(['stadium'], ['venue.id'], ),
    sa.ForeignKeyConstraint(['team'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamestat')
    # ### end Alembic commands ###
