"""empty message

Revision ID: 3ee1a49ef7f5
Revises: dd82b896e72c
Create Date: 2017-04-18 19:13:30.981932

"""

# revision identifiers, used by Alembic.
revision = '3ee1a49ef7f5'
down_revision = 'dd82b896e72c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ss_id', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('bats', sa.String(length=12), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('captain', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('draft_overall_pick', sa.Integer(), nullable=True),
    sa.Column('draft_round', sa.Integer(), nullable=True),
    sa.Column('draft_season', sa.Integer(), nullable=True),
    sa.Column('draft_team_name', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('handedness', sa.String(length=16), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('high_school', sa.String(length=128), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('humanized_salary', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=True),
    sa.Column('mlbam_id', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('position_abbreviation', sa.String(length=8), nullable=True),
    sa.Column('position_name', sa.String(length=32), nullable=True),
    sa.Column('pro_debut', sa.DateTime(), nullable=True),
    sa.Column('school', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('uniform_number', sa.Integer(), nullable=True),
    sa.Column('unit_of_height', sa.String(length=16), nullable=True),
    sa.Column('unit_of_weight', sa.String(length=16), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_ss_id'), 'player', ['ss_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_ss_id'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
