"""empty message

Revision ID: 527057b05a8e
Revises: f65354e62459
Create Date: 2017-04-13 21:25:41.651487

"""

# revision identifiers, used by Alembic.
revision = '527057b05a8e'
down_revision = 'f65354e62459'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('conference', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('division', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('division', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('team', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('team', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'updated_on')
    op.drop_column('team', 'created_on')
    op.drop_column('division', 'updated_on')
    op.drop_column('division', 'created_on')
    op.drop_column('conference', 'updated_on')
    op.drop_column('conference', 'created_on')
    # ### end Alembic commands ###
