"""empty message

Revision ID: 6998bbd58cf9
Revises: 3ee1a49ef7f5
Create Date: 2017-04-25 02:16:21.445784

"""

# revision identifiers, used by Alembic.
revision = '6998bbd58cf9'
down_revision = '3ee1a49ef7f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'humanized_salary',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'humanized_salary',
               existing_type=sa.String(length=16),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
