"""empty message

Revision ID: 6a8ee59ed2e1
Revises: None
Create Date: 2017-04-13 16:09:40.132997

"""

# revision identifiers, used by Alembic.
revision = '6a8ee59ed2e1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('conference', sa.String(length=32), nullable=True),
    sa.Column('division', sa.String(length=12), nullable=True),
    sa.Column('site_name', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_abbreviation'), 'team', ['abbreviation'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_abbreviation'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
