"""empty message

Revision ID: 779d965420b8
Revises: 6a8ee59ed2e1
Create Date: 2017-04-13 20:56:16.095252

"""

# revision identifiers, used by Alembic.
revision = '779d965420b8'
down_revision = '6a8ee59ed2e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('division',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=21), nullable=True),
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conference.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'team', sa.Column('colors', sa.JSON(), nullable=True))
    op.add_column(u'team', sa.Column('division_id', sa.Integer(), nullable=True))
    op.add_column(u'team', sa.Column('hashtags', sa.JSON(), nullable=True))
    op.add_column(u'team', sa.Column('latitude', sa.Numeric(precision=8, asdecimal=False), nullable=True))
    op.add_column(u'team', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column(u'team', sa.Column('longitude', sa.Numeric(precision=8, asdecimal=False), nullable=True))
    op.add_column(u'team', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column(u'team', sa.Column('nickname', sa.String(length=64), nullable=True))
    op.add_column(u'team', sa.Column('slug', sa.String(length=7), nullable=True))
    op.create_index(op.f('ix_team_slug'), 'team', ['slug'], unique=True)
    op.drop_index('ix_team_abbreviation', table_name='team')
    op.create_foreign_key(None, 'team', 'division', ['division_id'], ['id'])
    op.drop_column(u'team', 'conference')
    op.drop_column(u'team', 'division')
    op.drop_column(u'team', 'first_name')
    op.drop_column(u'team', 'last_name')
    op.drop_column(u'team', 'site_name')
    op.drop_column(u'team', 'city')
    op.drop_column(u'team', 'abbreviation')
    op.drop_column(u'team', 'state')
    op.drop_column(u'team', 'full_name')
    op.drop_column(u'team', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'team', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column(u'team', sa.Column('full_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column(u'team', sa.Column('state', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column(u'team', sa.Column('abbreviation', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column(u'team', sa.Column('city', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column(u'team', sa.Column('site_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column(u'team', sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column(u'team', sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column(u'team', sa.Column('division', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column(u'team', sa.Column('conference', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_index('ix_team_abbreviation', 'team', ['abbreviation'], unique=True)
    op.drop_index(op.f('ix_team_slug'), table_name='team')
    op.drop_column(u'team', 'slug')
    op.drop_column(u'team', 'nickname')
    op.drop_column(u'team', 'name')
    op.drop_column(u'team', 'longitude')
    op.drop_column(u'team', 'location')
    op.drop_column(u'team', 'latitude')
    op.drop_column(u'team', 'hashtags')
    op.drop_column(u'team', 'division_id')
    op.drop_column(u'team', 'colors')
    op.drop_table('division')
    op.drop_table('conference')
    # ### end Alembic commands ###
