"""empty message

Revision ID: dd82b896e72c
Revises: 487c693132ab
Create Date: 2017-04-14 15:07:02.846600

"""

# revision identifiers, used by Alembic.
revision = 'dd82b896e72c'
down_revision = '487c693132ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('ss_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_team_ss_id'), 'team', ['ss_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_ss_id'), table_name='team')
    op.drop_column('team', 'ss_id')
    # ### end Alembic commands ###
