"""empty message

Revision ID: f65354e62459
Revises: 779d965420b8
Create Date: 2017-04-13 21:01:45.819376

"""

# revision identifiers, used by Alembic.
revision = 'f65354e62459'
down_revision = '779d965420b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('ss_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_conference_ss_id'), 'conference', ['ss_id'], unique=True)
    op.add_column('division', sa.Column('ss_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_division_ss_id'), 'division', ['ss_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_division_ss_id'), table_name='division')
    op.drop_column('division', 'ss_id')
    op.drop_index(op.f('ix_conference_ss_id'), table_name='conference')
    op.drop_column('conference', 'ss_id')
    # ### end Alembic commands ###
