"""empty message

Revision ID: f81f5d9e0f90
Revises: 4d66d0222d0b
Create Date: 2017-04-27 19:57:48.166575

"""

# revision identifiers, used by Alembic.
revision = 'f81f5d9e0f90'
down_revision = '4d66d0222d0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
