FROM python:2.7
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
  apt-get install -y mysql-client vim && \
  rm -rf /var/lib/apt/lists/*

RUN mkdir -p /code/
WORKDIR /code

COPY hitparade/requirements.txt /code/
RUN pip install -r /code/requirements.txt

ADD hitparade/ /code/

CMD ["/usr/local/bin/python", "/code/cmd-celery.py"]
