FROM python:2.7
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
  apt-get install -y mysql-client nginx vim zip && \
  rm -rf /var/lib/apt/lists/* && \
  rm /etc/nginx/sites-available/default

RUN mkdir -p /code/ && mkdir -p /etc/uwsgi/
WORKDIR /code

COPY hitparade/requirements.txt /code/
RUN pip install -r /code/requirements.txt

ADD docker/entrypoint-web.sh /code/
ADD docker/hitparade-nginx.conf /etc/nginx/sites-enabled/
ADD docker/hitparade-uwsgi-params /etc/nginx/
ADD docker/hitparade-uwsgi.ini /etc/uwsgi/
ADD hitparade/ /code/

RUN chmod +x /code/entrypoint-web.sh

EXPOSE 80

CMD ["/code/entrypoint-web.sh"]
